services:
  - type: web
    name: student-university-chat-app
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt && cd app && python ../populate_data.py"
    startCommand: "gunicorn --chdir app server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
